****Specification:****

matrix-shape:   (5,5)

values:         1 to 10 

The matrix should be created in a manner in which absolute difference between **adjacent** elements in each column is between 3 to 5



In [2]:
import numpy as np

In [3]:
#initializing the array with zeros
arr_size = 5
arr = np.zeros((arr_size,arr_size))

In [4]:
arr

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [5]:
#Picking the first column
a = arr[:,0]
a.size

5

In [6]:
higher_limit = 10

In [7]:
a[0] = np.random.choice(higher_limit) + 1  #1 is added to make the range 1...10 from 0...9
a[0]

2.0

In [8]:
for i in range(1,arr_size):
    a[i] = np.random.choice(higher_limit) + 1
    #keep generating random number till the criterion is not met
    while not(np.abs(a[i] - a[i-1]) >= 3 and np.abs(a[i] - a[i-1]) <= 5):
        a[i] = np.random.choice(higher_limit) + 1 
    

In [9]:
a

array([  2.,   6.,   2.,   7.,  10.])

In [10]:
#Substituting the changed value of a as the first column of our array.
arr[:,0] = a

In [11]:
arr

array([[  2.,   0.,   0.,   0.,   0.],
       [  6.,   0.,   0.,   0.,   0.],
       [  2.,   0.,   0.,   0.,   0.],
       [  7.,   0.,   0.,   0.,   0.],
       [ 10.,   0.,   0.,   0.,   0.]])

In [12]:
#Repeating the same thing for all the columns of the array.
#Doing the whole process again, simultaneously for all columns of the array.
arr_size = 5
arr = np.zeros((arr_size,arr_size))
for column in range(arr_size):
    a = arr[:,column]
    a[0] = np.random.choice(higher_limit) + 1  #1 is added to make the range 1...10 from 0...9
    for i in range(1,arr_size):
        a[i] = np.random.choice(higher_limit) + 1 
        while not(np.abs(a[i] - a[i-1]) >= 3 and np.abs(a[i] - a[i-1]) <= 5):
            a[i] = np.random.choice(higher_limit) + 1 
    arr[:,column] = a



In [13]:
arr

array([[  2.,   6.,   9.,   3.,   1.],
       [  6.,  10.,   4.,   7.,   6.],
       [ 10.,   5.,   7.,   2.,   3.],
       [  5.,   2.,   3.,   7.,   8.],
       [  2.,   6.,   8.,   2.,   3.]])